// DTs de la web de Transfermarkt — [nombre,edad,nac,club,liga]
// Club vacío = sin equipo hoy (el juego los usa como técnicos libres).
window.DTS_DB=[
["Diego Flores",0,"","Instituto ACC","Liga ARG"],
["Guillermo Barros Schelotto",53,"ARG","Vélez Sarsfield","Liga ARG"],
["Darío Franco",0,"","Gimnasia (M)","Liga ARG"],
["Jádson Viera",0,"","Independiente","Liga ARG"],
["Julio Vaccari",0,"","Defensa","Liga ARG"],
["Frank Darío Kudelka",0,"","Newell's","Liga ARG"],
["Alexander Medina",0,"","Estudiantes LP","Liga ARG"],
["Guillermo Duró",0,"","Dep. Riestra","Liga ARG"],
["Mauricio Pellegrino",54,"ARG","Lanús","Liga ARG"],
["Rodolfo Arruabarrena",0,"","Boca Juniors","Liga ARG"],
["Sebastián Domínguez",0,"","Central Córdoba","Liga ARG"],
["Néstor Gorosito",0,"","San Lorenzo","Liga ARG"],
["Martín Palermo",0,"","Platense","Liga ARG"],
["Leonardo Madelón",62,"ARG","Unión Santa Fe","Liga ARG"],
["Jorge Sampaoli",65,"ARG","CA Talleres","Liga ARG"],
["Nicolás Diez",44,"ARG","Argentinos Jrs.","Liga ARG"],
["Ricardo Zielinski",66,"ARG","Belgrano","Liga ARG"],
["Jorge Almirón",0,"","Rosario Central","Liga ARG"],
["Facundo Sava",51,"ARG","Sarmiento Junin","Liga ARG"],
["Damián Ayude",49,"ARG","Barracas C.","Liga ARG"],
["Ariel Pereyra",0,"","Gimnasia","Liga ARG"],
["Julio César Falcioni",0,"","Atl. Tucumán","Liga ARG"],
["Diego Dabove",52,"ARG","Tigre","Liga ARG"],
["Diego Martínez",0,"","Huracán","Liga ARG"],
["Alfredo Berti",57,"ARG","Ind. Rivadavia","Liga ARG"],
["Pedro Troglio",60,"ARG","Banfield","Liga ARG"],
["Juan Pablo Vojvoda",50,"ARG","Racing Club","Liga ARG"],
["Rubén Forestello",0,"","Estudiantes RC","Liga ARG"],
["Eduardo Coudet",51,"ARG","River Plate","Liga ARG"],
["Israel Damonte",0,"","Aldosivi","Liga ARG"],
["Juan Sara",0,"","Ferro","Liga ARG"],
["Walter Otta",0,"","Dep. Morón","Liga ARG"],
["Iván Delfino",0,"","Colon","Liga ARG"],
["Andrés Montenegro",0,"","Almirante Brown","Liga ARG"],
["Luis García",0,"","Dep. Madryn","Liga ARG"],
["Pablo de Muner",0,"","Godoy Cruz","Liga ARG"],
["Alfredo Grelak",0,"","Estudiantes","Liga ARG"],
["Diego Funes",0,"","Ciudad Bolívar","Liga ARG"],
["Leonardo Lemos",0,"","Los Andes","Liga ARG"],
["Gustavo Coleoni",0,"","Racing (Cba)","Liga ARG"],
["Claudio Biaggio",0,"","Mitre (SdE)","Liga ARG"],
["Matías Módolo",0,"","San Miguel","Liga ARG"],
["Mauricio Giganti",0,"","All Boys","Liga ARG"],
["César Vigevani",0,"","Def. Belgrano","Liga ARG"],
["Mario Sciacqua",0,"","Central Norte","Liga ARG"],
["Marcelo Vázquez",0,"","San Telmo","Liga ARG"],
["Pedro Llorens",0,"","Chaco For Ever","Liga ARG"],
["Tobías Kohan",0,"","Acassuso","Liga ARG"],
["José María Martínez",0,"","Tristán Suárez","Liga ARG"],
["Hernán Pellerano",0,"","Gimnasia (J)","Liga ARG"],
["Nicolás Domingo",0,"","CA Temperley","Liga ARG"],
["Cristian Pellerano",0,"","Atlanta","Liga ARG"],
["Joaquín Iturrería",0,"","Midland","Liga ARG"],
["Juan Manuel Azconzábal",0,"","Gimnasia y Tiro","Liga ARG"],
["Enzo Imbesi",0,"","Dep. Maipú","Liga ARG"],
["Fernando Quiroz",0,"","Atl. Rafaela","Liga ARG"],
["Emanuel Tripodi",0,"","Quilmes","Liga ARG"],
["Alejandro Orfila",50,"URU","San Martín (T)","Liga ARG"],
["Leonardo Fernández",0,"","Colegiales","Liga ARG"],
["Carlos Mayor",0,"","Almagro","Liga ARG"],
["Alejandro Schiapparelli",0,"","San Martín (SJ)","Liga ARG"],
["Germán Lanaro",0,"","Nueva Chicago","Liga ARG"],
["Gabriel Gómez",0,"","Agropecuario","Liga ARG"],
["Sergio Rondina",0,"","Chacarita Jrs.","Liga ARG"],
["Marcelo Candia",0,"","Patronato","Liga ARG"],
["Mariano Munar",0,"","CA Güemes","Liga ARG"],
["Ivan Leko",0,"","Club Brugge","Bélgica"],
["Marvin Compper",0,"","Royal Antwerp","Bélgica"],
["Mario Kohnen",0,"","R Charleroi SC","Bélgica"],
["Rik De Mil",0,"","KAA Gent","Bélgica"],
["David Hubert",0,"","Union SG","Bélgica"],
["Michael Beale",0,"","Zulte Waregem","Bélgica"],
["Jess Thorup",0,"","Genk","Bélgica"],
["Vítor Bruno",0,"","RSC Anderlecht","Bélgica"],
["Tim Bakens",0,"","SK Beveren","Bélgica"],
["Lars Friis",0,"","Cercle Brugge","Bélgica"],
["Vincent Euvrard",0,"","Standard Liège","Bélgica"],
["Frédéric De Meyer",0,"","Sint-Truiden","Bélgica"],
["Lee Johnson",0,"","Lommel SK","Bélgica"],
["Frederik Vanderbiest",0,"","KV Mechelen","Bélgica"],
["Edward Still",0,"","La Louvière","Bélgica"],
["Issame Charaï",0,"","KVC Westerlo","Bélgica"],
["Timmy Simons",0,"","OH Leuven","Bélgica"],
["Michiel Jonckheere",0,"","KV Kortrijk","Bélgica"],
["Mauricio Soria",0,"","Always Ready","Bolivia"],
["Alejandro Restrepo",0,"","Bolívar","Bolivia"],
["Antônio Carlos Zago",0,"","The Strongest","Bolivia"],
["Flabio Torres",0,"","Real Potosí","Bolivia"],
["Leonardo Eguez",0,"","Guabirá","Bolivia"],
["Gustavo Florentín",0,"","Oriente P.","Bolivia"],
["Giancarlo Umaña",0,"","Aurora","Bolivia"],
["Thiago Leitão",0,"","Ind. Petrolero","Bolivia"],
["Erwin Sánchez",0,"","Club Blooming","Bolivia"],
["Eduardo Villegas",0,"","Nacional Potosí","Bolivia"],
["Bolívia",0,"","SA Bulo Bulo","Bolivia"],
["Nestor Colinas",0,"","Real Oruro","Bolivia"],
["Sebastián Núñez",0,"","Club A.B.B.","Bolivia"],
["Julio César Baldivieso",0,"","GV San José","Bolivia"],
["Jorge Alfonso",0,"","Real Tomayapo","Bolivia"],
["Wálter Flores",0,"","Univ. de Vinto","Bolivia"],
["Abel Ferreira",47,"POR","Palmeiras","Brasil"],
["Leonardo Jardim",51,"POR","Flamengo","Brasil"],
["Odair Hellmann",0,"","Athletico-PR","Brasil"],
["Marcão",0,"","Fluminense","Brasil"],
["Artur Jorge",0,"","Cruzeiro","Brasil"],
["Rogério Ceni",53,"BRA","EC Bahia","Brasil"],
["Vagner Mancini",0,"","RB Bragantino","Brasil"],
["Eduardo Domínguez",47,"ARG","Atlético-MG","Brasil"],
["Fernando Diniz",51,"BRA","Corinthians","Brasil"],
["Fernando Seabra",0,"","Coritiba FC","Brasil"],
["Luis Alberto Piedrahita",0,"","Botafogo","Brasil"],
["Jair Ventura",0,"","EC Vitória","Brasil"],
["Dorival Júnior",63,"BRA","São Paulo","Brasil"],
["Cuca",0,"","Santos","Brasil"],
["Luís Castro",0,"","Grêmio","Brasil"],
["Paulo Pezzolano",0,"","Internacional","Brasil"],
["Rafael Guanaes",0,"","Mirassol-SP","Brasil"],
["Léo Condé",0,"","Remo","Brasil"],
["Pedro Emanuel",0,"","Vasco da Gama","Brasil"],
["Rafael Lacerda",0,"","Chapecoense","Brasil"],
["Eduardo Baptista",0,"","Criciúma","Brasil"],
["Maurício Barbieri",0,"","Juventude","Brasil"],
["Guto Ferreira",0,"","Vila Nova FC","Brasil"],
["Paulo Autuori",0,"","Fortaleza","Brasil"],
["Luizinho Lopes",0,"","Operário-PR","Brasil"],
["Gilmar Dal Pozzo",0,"","Sport Recife","Brasil"],
["Enderson Moreira",0,"","Novorizontino","Brasil"],
["Alex",0,"","Athletic","Brasil"],
["Fábio Matias",0,"","CRB","Brasil"],
["Roger Silva",0,"","Atlético-GO","Brasil"],
["Mozart",0,"","Goiás","Brasil"],
["Vinícius",0,"","São Bernardo","Brasil"],
["Claudio Tencati",0,"","Botafogo-SP","Brasil"],
["Hélio dos Anjos",0,"","Náutico","Brasil"],
["Eduardo Barros",0,"","Cuiabá-MT","Brasil"],
["Daniel Paulista",0,"","Ceará SC","Brasil"],
["Allan Aal",0,"","Avaí FC","Brasil"],
["Rogério Micale",0,"","Londrina-PR","Brasil"],
["Umberto Louzer",0,"","América-MG","Brasil"],
["Márcio Zanardi",0,"","Ponte Preta","Brasil"],
["Fernando Ortiz",0,"","Colo-Colo","Chile"],
["Fernando Gago",0,"","U. de Chile","Chile"],
["Daniel Garnero",0,"","U. Católica","Chile"],
["Guillermo Farré",45,"ARG","Palestino","Chile"],
["Juan José Ribera",0,"","Ñublense","Chile"],
["Walter Ribonetto",47,"ARG","CD Everton","Chile"],
["Fernando Díaz",0,"","D. Concepción","Chile"],
["Hernán Caputto",0,"","Coquimbo Unido","Chile"],
["Víctor Rivero",0,"","Limache","Chile"],
["Lucas Bovaglio",0,"","O'Higgins","Chile"],
["Jaime García",0,"","Huachipato","Chile"],
["Felipe Gutiérrez",0,"","La Serena","Chile"],
["Patricio Graff",0,"","Audax Italiano","Chile"],
["Cristián Muñoz",0,"","U. Concepción","Chile"],
["Gustavo Huerta",0,"","Cobresal","Chile"],
["Martín Cicotello",0,"","La Calera","Chile"],
["David González",0,"","CD América","Colombia"],
["Luis Amaranto Perea",0,"","Indep. Medellín","Colombia"],
["Sebastián Oliveros",0,"","Deportes Tolima","Colombia"],
["Pablo Peirano",0,"","A. Bucaramanga","Colombia"],
["José Luis García",0,"","Llaneros FC","Colombia"],
["Rafael Dudamel",0,"","Deportivo Cali","Colombia"],
["Flavio Robatto",0,"","Rionegro Águila","Colombia"],
["Fabián Bustos",0,"","Millonarios","Colombia"],
["Hernán Herrera",0,"","Once Caldas","Colombia"],
["Diego Arias",0,"","Fortaleza CEIF","Colombia"],
["Pablo Repetto",0,"","Indep. Santa Fe","Colombia"],
["Lucas González Vélez",0,"","Atl. Nacional","Colombia"],
["Ricardo Valiño",0,"","Inter Bogotá","Colombia"],
["Arturo Reyes",0,"","Pereira","Colombia"],
["Camilo Ayala",0,"","Alianza FC","Colombia"],
["Nicolás Chiesa",0,"","Cúcuta Dep.","Colombia"],
["Hubert Bodhert",0,"","Jaguares FC","Colombia"],
["Alfredo Arias",0,"","Junior FC","Colombia"],
["Jonathan Risueño",0,"","Deportivo Pasto","Colombia"],
["Jhon Jaime Gómez",0,"","Boyacá Chicó","Colombia"],
["Joaquín Papa",0,"","Independiente","Ecuador"],
["Guillermo Sanguinetti",0,"","CD Macará","Ecuador"],
["Norberto Araujo",0,"","SD Aucas","Ecuador"],
["Diego Martínez",0,"","Uni. Católica","Ecuador"],
["Gustavo Álvarez",0,"","LDU Quito","Ecuador"],
["Pablo Trobbiani",0,"","Barcelona SC","Ecuador"],
["Matías Córdoba",0,"","Leones FC","Ecuador"],
["Juan Pablo Buch",0,"","Libertad FC","Ecuador"],
["Paúl Vélez",0,"","Mushuc Runa SC","Ecuador"],
["Cristian Nasuti",0,"","CS Emelec","Ecuador"],
["Daniel Néculman",0,"","Dep. Cuenca","Ecuador"],
["Pool Gavilánez",0,"","Guayaquil City","Ecuador"],
["Hólger Matamoros",0,"","Orense SC","Ecuador"],
["Bernardo Redín",0,"","Técnico U.","Ecuador"],
["Juan Carlos León",0,"","Delfín SC","Ecuador"],
["Raúl Duarte",0,"","Manta FC","Ecuador"],
["Mikel Arteta",43,"ESP","Arsenal","Premier"],
["Unai Emery",54,"ESP","Aston Villa","Premier"],
["Marco Rose",0,"","Bournemouth","Premier"],
["Keith Andrews",45,"IRL","Brentford","Premier"],
["Fabian Hürzeler",33,"ALE","Brighton","Premier"],
["Xabi Alonso",44,"ESP","Chelsea","Premier"],
["Frank Lampard",0,"","Coventry","Premier"],
["Pierre Sage",46,"FRA","Crystal Palace","Premier"],
["David Moyes",62,"ESC","Everton","Premier"],
["Álvaro Arbeloa",0,"","Fulham","Premier"],
["Sergej Jakirovic",0,"","Hull City","Premier"],
["Gary O'Neil",0,"","Ipswich","Premier"],
["Daniel Farke",49,"ALE","Leeds","Premier"],
["Andoni Iraola",43,"ESP","Liverpool","Premier"],
["Enzo Maresca",46,"ITA","Man City","Premier"],
["Michael Carrick",0,"","Man Utd","Premier"],
["Matthias Jaissle",0,"","Newcastle","Premier"],
["Oliver Glasner",51,"AUT","Nott'm Forest","Premier"],
["Régis Le Bris",50,"FRA","Sunderland","Premier"],
["Roberto De Zerbi",46,"ITA","Tottenham","Premier"],
["Julien Stéphan",0,"","QPR","Premier"],
["Alex Neil",0,"","Millwall","Premier"],
["Steven Schumacher",0,"","Bolton","Premier"],
["Nathan Jones",0,"","Charlton","Premier"],
["Kim Hellberg",0,"","Middlesbrough","Premier"],
["Vítor Matos",0,"","Swansea","Premier"],
["Alessio Dionisi",0,"","Watford","Premier"],
["James Morrison",0,"","West Brom","Premier"],
["Tony Mowbray",0,"","Blackburn","Premier"],
["Nicky Hayen",0,"","Burnley","Premier"],
["Nuno Espírito Santo",0,"","West Ham","Premier"],
["César Peixoto",0,"","Wolves","Premier"],
["Brian Barry-Murphy",0,"","Cardiff","Premier"],
["Phil Parkinson",0,"","Wrexham","Premier"],
["Chris Davies",0,"","Birmingham","Premier"],
["Chris Wilder",0,"","Sheff Utd","Premier"],
["John Eustace",0,"","Derby","Premier"],
["Tom Shaw",0,"","Lincoln City","Premier"],
["Philippe Clement",0,"","Norwich","Premier"],
["Paul Heckingbottom",0,"","Preston","Premier"],
["Mark Robins",0,"","Stoke City","Premier"],
["John Mousinho",0,"","Portsmouth","Premier"],
["Michael Skubala",0,"","Bristol City","Premier"],
["Tonda Eckert",0,"","Southampton","Premier"],
["Luis Enrique",55,"ESP","PSG","Francia"],
["Dino Toppmöller",45,"ALE","Lens","Francia"],
["Davide Ancelotti",36,"ITA","Lille","Francia"],
["Paulo Fonseca",52,"POR","Lyon","Francia"],
["Bruno Genesio",59,"FRA","Marseille","Francia"],
["Franck Haise",54,"FRA","Stade Rennais","Francia"],
["Filipe Luís",40,"BRA","Monaco","Francia"],
["Hugo Oliveira",0,"","R. Strasbourg","Francia"],
["Alexandre Dujeux",47,"FRA","FC Lorient","Francia"],
["Jens Berthel Askou",0,"","Toulouse","Francia"],
["Liam Rosenior",41,"ING","Paris FC","Francia"],
["Julien Lachuer",0,"","Stade Brestois","Francia"],
["Stéphane Gilli",51,"FRA","Angers SCO","Francia"],
["Didier Digard",39,"FRA","Le Havre AC","Francia"],
["Will Still",0,"","AJ Auxerre","Francia"],
["Olivier Pantaloni",59,"FRA","Nice","Francia"],
["Stéphane Dumont",0,"","Troyes","Francia"],
["Patrick Videira",0,"","Le Mans FC","Francia"],
["Vincent Kompany",39,"BEL","Bayern Munich","Alemania"],
["Niko Kovac",54,"CRO","Dortmund","Alemania"],
["Martín Demichelis",0,"","Leipzig","Alemania"],
["Sebastian Hoeneß",43,"ALE","Stuttgart","Alemania"],
["Christian Ilzer",48,"AUT","Hoffenheim","Alemania"],
["Carles Martínez",41,"ESP","Leverkusen","Alemania"],
["Julian Schuster",40,"ALE","Freiburg","Alemania"],
["Adi Hütter",0,"","Frankfurt","Alemania"],
["Manuel Baum",0,"","Augsburg","Alemania"],
["Urs Fischer",0,"","Mainz","Alemania"],
["Mauro Lustrinelli",0,"","Union Berlin","Alemania"],
["Eugen Polanski",39,"ALE","Mönchengladbach","Alemania"],
["Merlin Polzin",35,"ALE","Hamburg","Alemania"],
["René Wagner",0,"","1.FC Köln","Alemania"],
["Daniel Thioune",0,"","Werder Bremen","Alemania"],
["Miron Muslic",0,"","FC Schalke 04","Alemania"],
["Vincent Wagner",0,"","SV Elversberg","Alemania"],
["Ralf Kettemann",0,"","SC Paderborn","Alemania"],
["Marko Nikolic",0,"","AEK Athens","Grecia"],
["José Luis Mendilibar",0,"","Olympiacos","Grecia"],
["Alessio Lisci",0,"","PAOK","Grecia"],
["Jacob Neestrup",0,"","Panathinaikos","Grecia"],
["Michalis Grigoriou",0,"","Aris Saloniki","Grecia"],
["Elias Charalambous",0,"","Levadiakos","Grecia"],
["Christos Kontis",0,"","OFI Crete","Grecia"],
["Konstantinos Bratsos",0,"","Volos","Grecia"],
["Dusan Kerkez",0,"","Atromitos","Grecia"],
["Sebastián Leto",0,"","Kifisia","Grecia"],
["Georgios Antonopoulos",0,"","Asteras Aktor","Grecia"],
["Giannis Anastasiou",0,"","Panetolikos","Grecia"],
["Panagiotis Christofileas",0,"","Kalamata","Grecia"],
["Walter Mazzarri",0,"","Iraklis","Grecia"],
["Cristian Chivu",45,"RUM","Inter","Italia"],
["Massimiliano Allegri",58,"ITA","Napoli","Italia"],
["Gian Piero Gasperini",68,"ITA","Roma","Italia"],
["Cesc Fàbregas",38,"ESP","Como","Italia"],
["Rúben Amorim",0,"","AC Milan","Italia"],
["Luciano Spalletti",67,"ITA","Juventus","Italia"],
["Maurizio Sarri",67,"ITA","Atalanta","Italia"],
["Domenico Tedesco",0,"","Bologna","Italia"],
["Gennaro Gattuso",0,"","Lazio","Italia"],
["Kosta Runjaić",0,"","Udinese","Italia"],
["Alberto Aquilani",0,"","Sassuolo","Italia"],
["Ignazio Abate",0,"","Torino","Italia"],
["Carlos Cuesta",30,"ESP","Parma","Italia"],
["Fabio Pisacane",40,"ITA","Cagliari","Italia"],
["Fabio Grosso",48,"ITA","Fiorentina","Italia"],
["Daniele De Rossi",42,"ITA","Genoa","Italia"],
["Eusebio Di Francesco",56,"ITA","Lecce","Italia"],
["Giovanni Stroppa",0,"","Venezia","Italia"],
["Massimiliano Alvini",0,"","Frosinone","Italia"],
["Ivan Jurić",0,"","Monza","Italia"],
["Paolo Bianco",0,"","Pisa","Italia"],
["Marco Baroni",62,"ITA","Hellas Verona","Italia"],
["Marco Giampaolo",0,"","Cremonese","Italia"],
["Filippo Inzaghi",0,"","Palermo","Italia"],
["Giorgio Gorgone",0,"","Catanzaro","Italia"],
["Daniele Galloppa",0,"","Modena","Italia"],
["Alessandro Nesta",0,"","Avellino","Italia"],
["Antonio Nicola Calabro",0,"","Padova","Italia"],
["Alessandro Diamanti",0,"","Cesena","Italia"],
["Francesco Modesto",0,"","Mantova","Italia"],
["Gabriele Cioffi",0,"","Carrarese","Italia"],
["Bernardo Corradi",0,"","Sampdoria","Italia"],
["Andrea Chiappella",0,"","Virtus Entella","Italia"],
["Guido Pagliuca",0,"","FC Empoli","Italia"],
["Davide Possanzini",0,"","Südtirol","Italia"],
["Antonio Floro Flores",0,"","Benevento","Italia"],
["Fabio Gallo",0,"","LR Vicenza","Italia"],
["Cristian Bucchi",0,"","Arezzo","Italia"],
["Francesco Tomei",0,"","Ascoli","Italia"],
["Pietro De Giorgio",0,"","Juve Stabia","Italia"],
["Guillermo Almada",0,"","América","Liga MX"],
["Miguel Herrera",0,"","Atlante","Liga MX"],
["Hernán Crespo",50,"ARG","Atlas","Liga MX"],
["Joel Huiqui",0,"","CD Cruz Azul","Liga MX"],
["Gabriel Milito",0,"","Chivas","Liga MX"],
["Sebastián Abreu",0,"","Club Tijuana","Liga MX"],
["Pedro Malta",0,"","FC Juárez","Liga MX"],
["Javier Gandolfi",0,"","León","Liga MX"],
["Matías Almeyda",52,"ARG","Monterrey","Liga MX"],
["Martín Varini",0,"","Necaxa","Liga MX"],
["Benjamín Mora",0,"","Pachuca","Liga MX"],
["Albert Espigares",0,"","Puebla FC","Liga MX"],
["Esteban González",0,"","Querétaro FC","Liga MX"],
["Diego Mejía",0,"","San Luis","Liga MX"],
["Renato Paiva",0,"","Santos Laguna","Liga MX"],
["Juninho",0,"","Tigres UANL","Liga MX"],
["Antonio Mohamed",0,"","Toluca","Liga MX"],
["Esteban Solari",0,"","UNAM Pumas","Liga MX"],
["Lee-Roy Echteld",0,"","AZ Alkmaar","Holanda"],
["Dick Lukkien",0,"","FC Groningen","Holanda"],
["Joseph Oosting",0,"","Go Ahead Eagles","Holanda"],
["Danny Buijs",0,"","Fortuna Sittard","Holanda"],
["Míchel Sánchez",50,"ESP","Ajax","Holanda"],
["Peter Bosz",0,"","PSV","Holanda"],
["Giovanni van Bronckhorst",0,"","Feyenoord","Holanda"],
["Robin Veldman",0,"","Heerenveen","Holanda"],
["Ruben den Uil",0,"","Excelsior","Holanda"],
["Dick Schreuder",0,"","NEC Nijmegen","Holanda"],
["John van den Brom",0,"","FC Twente","Holanda"],
["Rogier Meijer",0,"","Sparta R.","Holanda"],
["Henk Brugge",0,"","Telstar","Holanda"],
["Anthony Correia",0,"","Utrecht","Holanda"],
["Henry van der Vegt",0,"","PEC Zwolle","Holanda"],
["Robin Peter",0,"","ADO Den Haag","Holanda"],
["John Stegeman",0,"","Willem II","Holanda"],
["Johan Plat",0,"","SC Cambuur","Holanda"],
["Eduardo Ledesma",0,"","2 de Mayo","Paraguay"],
["Nelson Valdez",0,"","Libertad","Paraguay"],
["José Arrúa",0,"","Trinidense","Paraguay"],
["Ariel Galeano",0,"","Guaraní","Paraguay"],
["Jorge González",0,"","Recoleta FC","Paraguay"],
["Pablo Sánchez",0,"","Olimpia","Paraguay"],
["Ariel Holan",65,"ARG","Cerro Porteño","Paraguay"],
["Víctor Bernay",0,"","Nacional","Paraguay"],
["Roberto Nanni",0,"","CS Ameliano","Paraguay"],
["Rodrigo López",0,"","Luqueño","Paraguay"],
["Javier Torrente",0,"","Rubio Ñú","Paraguay"],
["Troadio Duarte",0,"","CS San Lorenzo","Paraguay"],
["Pablo Guede",0,"","Alianza Lima","Perú"],
["Walter Paolella",0,"","Los Chankas","Perú"],
["Horacio Melgarejo",0,"","Cienciano","Perú"],
["Héctor Cúper",0,"","Universitario","Perú"],
["Miguel Rondelli",0,"","FBC Melgar","Perú"],
["Javier Rabanal",0,"","Cusco FC","Perú"],
["Lisandro Greppo",0,"","Dep. Garcilaso","Perú"],
["Federico Urciuoli",0,"","Alianza Atl.","Perú"],
["José Eugenio Hernández",0,"","Comerciantes","Perú"],
["Francisco Usúcar",0,"","AD Tarma","Perú"],
["Carlos Desio",0,"","Sport Boys","Perú"],
["Roberto Mosquera",0,"","Sport. Cristal","Perú"],
["Cristian Paulucci",0,"","UTC","Perú"],
["Jaime Serna",0,"","Dep. Moquegua","Perú"],
["Celso Ayala",0,"","FC Cajamarca","Perú"],
["Gerardo Ameli",0,"","Atlético Grau","Perú"],
["Richard Pellejero",0,"","Sport Huancayo","Perú"],
["Jorge Araujo",0,"","Juan Pablo II","Perú"],
["Vasco Seabra",0,"","Arouca","Portugal"],
["Francesco Farioli",0,"","Porto","Portugal"],
["Mitchell van der Gaag",0,"","Marítimo","Portugal"],
["Marco Silva",48,"POR","Benfica","Portugal"],
["João Gião",0,"","Nacional","Portugal"],
["Rui Borges",0,"","Sporting","Portugal"],
["Petit",0,"","Santa Clara","Portugal"],
["Luís Pinto",0,"","Gil Vicente","Portugal"],
["Pepa",0,"","Estrela Amadora","Portugal"],
["Carlos Vicens",0,"","Braga","Portugal"],
["Carlos Carvalhal",0,"","Famalicão","Portugal"],
["Bruno Pinheiro",0,"","Académico Viseu","Portugal"],
["Sérgio Ferreira",0,"","Alverca","Portugal"],
["Vasco Matos",0,"","Estoril","Portugal"],
["Vasco Botelho da Costa",0,"","Moreirense","Portugal"],
["Tiago Margarido",0,"","Vit. Guimarães","Portugal"],
["Sotiris Sylaidopoulos",0,"","Rio Ave","Portugal"],
["Filipe Coelho",0,"","Casa Pia","Portugal"],
["Murad Musaev",0,"","Krasnodar","Rusia"],
["Sergey Semak",0,"","Zenit S-Pb","Rusia"],
["Juan Carlos Carcedo",0,"","Spartak Moscow","Rusia"],
["Vadim Evseev",0,"","Dinamo Makhach.","Rusia"],
["Dmitriy Igdisamov",0,"","CSKA Moscow","Rusia"],
["Andrey Talalaev",0,"","Baltika","Rusia"],
["Jonatan Alba",0,"","Rostov","Rusia"],
["Franc Artiga",0,"","Rubin Kazan","Rusia"],
["Ildar Akhmetzyanov",0,"","Orenburg","Rusia"],
["Sandro Schwarz",0,"","Dynamo Moscow","Rusia"],
["Juan Díaz",0,"","Rodina Moscow","Rusia"],
["Mikhail Galaktionov",0,"","Loko Moscow","Rusia"],
["Stanislav Cherchesov",0,"","Akhmat Grozny","Rusia"],
["Sergey Bulatov",0,"","KS Samara","Rusia"],
["Srdjan Blagojevic",0,"","Akron Tolyatti","Rusia"],
["Oleg Vasilenko",0,"","Fakel Voronezh","Rusia"],
["Ange Postecoglou",0,"","Al-Nassr","Arabia"],
["Arthur Papas",0,"","Al-Ettifaq","Arabia"],
["Simone Inzaghi",0,"","Al-Hilal","Arabia"],
["Brendan Rodgers",0,"","Al-Qadsiah","Arabia"],
["Jalel Kadri",0,"","Al-Hazem","Arabia"],
["Christophe Galtier",0,"","NEOM SC","Arabia"],
["Marino Pusic",0,"","Al-Ahli","Arabia"],
["Jens Wissing",0,"","Al-Ittihad","Arabia"],
["Des Buckingham",0,"","Al-Kholood","Arabia"],
["José Gomes",0,"","Al-Khaleej","Arabia"],
["Zarko Lazetic",0,"","Al-Taawoun","Arabia"],
["Damir Buric",0,"","Abha","Arabia"],
["Fábio Carille",0,"","Al-Fayha","Arabia"],
["Bruno Lage",0,"","Al-Diriyah","Arabia"],
["Giovanni Solinas",0,"","Al-Faisaly","Arabia"],
["Maurício Dulac",0,"","Al-Riyadh","Arabia"],
["Thomas Letsch",0,"","Al-Shabab","Arabia"],
["Khaled Al-Atwi",0,"","Al-Fateh","Arabia"],
["Manolo González",47,"ESP","Espanyol","España"],
["Quique Sánchez Flores",0,"","Alavés","España"],
["Luis García",0,"","Sevilla FC","España"],
["Iñigo Pérez",0,"","Villarreal","España"],
["José Alberto López",0,"","Racing","España"],
["Martín Anselmi",0,"","Elche CF","España"],
["Antonio Hidalgo",0,"","Dep. A Coruña","España"],
["Hansi Flick",61,"ALE","Barcelona","España"],
["José Mourinho",0,"","Real Madrid","España"],
["Diego Simeone",55,"ARG","Atlético","España"],
["Manuel Pellegrini",72,"CHI","Real Betis","España"],
["Claudio Giráldez",38,"ESP","Celta de Vigo","España"],
["Carlos Corberán",43,"ESP","Valencia","España"],
["Pellegrino Matarazzo",0,"","Real Sociedad","España"],
["Edin Terzic",0,"","Athletic Club","España"],
["Luis Miguel Ramis",0,"","CA Osasuna","España"],
["Juan Funes",0,"","Málaga CF","España"],
["Beñat San José",0,"","Rayo Vallecano","España"],
["José Bordalás",61,"ESP","Getafe","España"],
["Luís Castro",0,"","Levante","España"],
["Carles Manso",0,"","FC Andorra","España"],
["Xavier García Pimienta",0,"","UD Almería","España"],
["Álvaro Cervera",0,"","CD Tenerife","España"],
["Luis García",0,"","RCD Mallorca","España"],
["Sergio Francisco",47,"ESP","Burgos CF","España"],
["Rubén de la Barrera",0,"","UD Las Palmas","España"],
["Pablo Hernández",0,"","Castellón","España"],
["Quique Álvarez",0,"","Girona","España"],
["Rubén Albés",0,"","CD Leganés","España"],
["Julián Calero",0,"","Real Oviedo","España"],
["Nicolás Larcamón",0,"","Sporting Gijón","España"],
["Pacheta",0,"","Granada CF","España"],
["Albert Celades",0,"","Cádiz CF","España"],
["Ferran Costa",0,"","CE Sabadell","España"],
["Fredi Álvarez",0,"","Celta Fortuna","España"],
["Iván Ania",0,"","Córdoba CF","España"],
["Alberto González",0,"","Albacete","España"],
["Ion Ansotegi",0,"","Real Sociedad B","España"],
["Jokin Aranbarri",0,"","SD Eibar","España"],
["Fran Escribá",0,"","Real Valladolid","España"],
["Claudio Barragán",0,"","Eldense","España"],
["José Juan Romero",0,"","AD Ceuta","España"],
["Besnik Hasi",0,"","Amed SK","Turquía"],
["Nuri Şahin",0,"","Basaksehir","Turquía"],
["Metin Diyadin",0,"","Genclerbirligi","Turquía"],
["Vincenzo Italiano",48,"ITA","Besiktas","Turquía"],
["Recep Uçar",0,"","C. Rizespor","Turquía"],
["Stanimir Stoilov",0,"","Göztepe","Turquía"],
["Thorsten Fink",0,"","Samsunspor","Turquía"],
["Péter Szabó",0,"","Galatasaray","Turquía"],
["Uğur Uçar",0,"","Corum FK","Turquía"],
["Fatih Tekke",0,"","Trabzonspor","Turquía"],
["João Pereira",0,"","Alanyaspor","Turquía"],
["Mirel Rădoi",0,"","Gaziantep FK","Turquía"],
["Emre Belözoğlu",0,"","Kasimpasa","Turquía"],
["İsmail Kartal",0,"","Fenerbahçe","Turquía"],
["İlhan Palut",0,"","Konyaspor","Turquía"],
["Özhan Pulat",0,"","Eyüpspor","Turquía"],
["Selçuk İnan",0,"","Kocaelispor","Turquía"],
["Serkan Özbalta",0,"","Erzurumspor FK","Turquía"],
["B.J. Callaghan",0,"","Nashville","MLS"],
["Guillermo Hoyos",0,"","Miami","MLS"],
["Gregg Berhalter",0,"","Chicago","MLS"],
["Marko Mitrovic",0,"","New England","MLS"],
["Dean Smith",0,"","Charlotte","MLS"],
["Pat Noonan",0,"","Cincinnati","MLS"],
["Pascal Jansen",0,"","New York City","MLS"],
["Michael Bradley",0,"","New York","MLS"],
["René Weiler",0,"","D.C. United","MLS"],
["Martín Perelman",0,"","Orlando","MLS"],
["Laurent Courtois",0,"","Columbus","MLS"],
["Robin Fraser",0,"","Toronto","MLS"],
["Ryan Richter",0,"","Philadelphia","MLS"],
["Philippe Eullaffroy",0,"","Montréal","MLS"],
["Tata Martino",0,"","Atlanta","MLS"],
["Jesper Sørensen",0,"","Vancouver","MLS"],
["Ben Olsen",0,"","Houston","MLS"],
["Marc Dos Santos",0,"","LAFC","MLS"],
["Bruce Arena",0,"","SJ Earthquakes","MLS"],
["Eric Quill",0,"","Dallas","MLS"],
["Yoann Damet",0,"","St. Louis CITY","MLS"],
["Pablo Mastroeni",0,"","Salt Lake","MLS"],
["Matt Wells",0,"","Colorado","MLS"],
["Cameron Knowles",0,"","Minnesota","MLS"],
["Mikey Varas",0,"","San Diego","MLS"],
["Martí Cifuentes",0,"","Portland","MLS"],
["Brian Schmetzer",0,"","Seattle","MLS"],
["Greg Vanney",0,"","LA Galaxy","MLS"],
["Davy Arnaud",0,"","Austin","MLS"],
["Raphael Wicky",0,"","Kansas City","MLS"],
["Jorge Fossati",0,"","Liverpool FC","Uruguay"],
["Alejandro Cappuccio",0,"","CA Cerro","Uruguay"],
["Cristian Chambian",0,"","Racing Club","Uruguay"],
["Gabriel Di Noia",0,"","CD Maldonado","Uruguay"],
["Mathías Corujo",0,"","Wanderers","Uruguay"],
["Ignacio Ithurralde",0,"","Boston River","Uruguay"],
["Diego Aguirre",0,"","Peñarol","Uruguay"],
["Marcelo Méndez",0,"","Mvd City Torque","Uruguay"],
["Diego Osella",0,"","Central Español","Uruguay"],
["Danielo Núñez",0,"","Cerro Largo","Uruguay"],
["Sergio Blanco",0,"","Juventud","Uruguay"],
["Leonel Rocco",0,"","Danubio FC","Uruguay"],
["Federico Nieves",0,"","Albion FC","Uruguay"],
["Daniel Carreño",0,"","Nacional","Uruguay"],
["Tabaré Silva",0,"","CA Progreso","Uruguay"],
["Mauricio Larriera",0,"","Defensor SC","Uruguay"],
["Álvaro Recoba",0,"","Táchira","Venezuela"],
["Héctor Bidoglio",0,"","Dep. La Guaira","Venezuela"],
["Eduardo Saragó",0,"","Puerto Cabello","Venezuela"],
["Francesco Stifano",0,"","Metropolitanos","Venezuela"],
["Leo González",0,"","Portuguesa FC","Venezuela"],
["Jesús Gómez",0,"","Estudiantes","Venezuela"],
["Daniel Farías",0,"","Carabobo FC","Venezuela"],
["Henry Meléndez",0,"","Caracas FC","Venezuela"],
["Johannys Garcia",0,"","Rayo Zuliano","Venezuela"],
["Jesús Ortíz",0,"","Monagas SC","Venezuela"],
["Pedro Vera",0,"","Trujillanos","Venezuela"],
["Daniel Sasso",0,"","UCV FC","Venezuela"],
["Giancarlo Maldonado",0,"","Anzoátegui","Venezuela"],
["Josue Ortíz",0,"","Zamora FC","Venezuela"],
["Claudio Úbeda",56,"ARG","","Liga ARG"],
["Marcelo Gallardo",50,"ARG","","Liga ARG"],
["Gustavo Costas",63,"ARG","","Liga ARG"],
["Gustavo Quinteros",61,"ARG","","Liga ARG"],
["Carlos Tevez",42,"ARG","","Liga ARG"],
["Frank Kudelka",65,"ARG","","Liga ARG"],
["Cristian Fabbiani",42,"ARG","","Liga ARG"],
["Daniel Oldrá",57,"ARG","","Liga ARG"],
["Omar De Felippe",64,"ARG","","Liga ARG"],
["Rubén Insúa",64,"ARG","","Liga ARG"],
["Mariano Soso",45,"ARG","","Liga ARG"],
["Cristian González",51,"ARG","","Liga ARG"],
["Lucas Pusineri",50,"ARG","","Liga ARG"],
["Gustavo Benítez",51,"PAR","","Liga ARG"],
["Marcelino García",60,"ESP","","España"],
["Ernesto Valverde",62,"ESP","","España"],
["Íñigo Pérez",38,"ESP","","España"],
["Jagoba Arrasate",47,"ESP","","España"],
["Eder Sarabia",45,"ESP","","España"],
["Pep Guardiola",55,"ESP","","Premier"],
["Arne Slot",47,"HOL","","Premier"],
["Ruben Amorim",41,"POR","","Premier"],
["Thomas Frank",52,"DIN","","Premier"],
["Eddie Howe",48,"ING","","Premier"],
["Sean Dyche",54,"ING","","Premier"],
["Scott Parker",45,"ING","","Premier"],
["Antonio Conte",56,"ITA","","Italia"],
["Raffaele Palladino",41,"ITA","","Italia"],
["Paolo Vanoli",53,"ITA","","Italia"],
["Kosta Runjaic",54,"ALE","","Italia"],
["Davide Nicola",53,"ITA","","Italia"],
["Alberto Gilardino",43,"ITA","","Italia"],
["Paolo Zanetti",43,"ITA","","Italia"],
["Kasper Hjulmand",53,"DIN","","Alemania"],
["Ole Werner",37,"ALE","","Alemania"],
["Bo Henriksen",51,"DIN","","Alemania"],
["Steffen Baumgart",54,"ALE","","Alemania"],
["Horst Steffen",56,"ALE","","Alemania"],
["Sandro Wagner",38,"ALE","","Alemania"],
["Lukas Kwasniok",44,"ALE","","Alemania"],
["Sébastien Pocognoli",38,"BEL","","Francia"],
["Habib Beye",48,"SEN","","Francia"],
["Eric Roy",58,"FRA","","Francia"],
["Christophe Pélissier",60,"FRA","","Francia"],
["Mano Menezes",63,"BRA","","Brasil"],
["Ramón Díaz",66,"ARG","","Brasil"],
["Luis Zubeldía",45,"ARG","","Brasil"]
];
