// ═══════════════════════════════════════════════════════════════
// BASE DE DTs REALES — temporada 2025/26
// La API de SportDB no expone entrenadores, así que esta base se
// cura a mano. Formato: [nombre, edad, nacionalidad, club, liga]
// Los nombres de club coinciden con los de players-db.js.
// ═══════════════════════════════════════════════════════════════
window.DTS_DB=[
// ── LIGA ARGENTINA ──
['Claudio Úbeda',56,'ARG','Boca Juniors','Liga ARG'],
['Marcelo Gallardo',50,'ARG','River Plate','Liga ARG'],
['Gustavo Costas',63,'ARG','Racing Club','Liga ARG'],
['Gustavo Quinteros',61,'ARG','Independiente','Liga ARG'],
['Damián Ayude',49,'ARG','San Lorenzo','Liga ARG'],
['Guillermo Barros Schelotto',53,'ARG','Vélez Sarsfield','Liga ARG'],
['Eduardo Domínguez',47,'ARG','Estudiantes LP','Liga ARG'],
['Ariel Holan',65,'ARG','Rosario Central','Liga ARG'],
['Carlos Tevez',42,'ARG','CA Talleres','Liga ARG'],
['Mauricio Pellegrino',54,'ARG','Lanús','Liga ARG'],
['Frank Kudelka',65,'ARG','Huracán','Liga ARG'],
['Nicolás Diez',44,'ARG','Argentinos Jrs.','Liga ARG'],
['Pedro Troglio',60,'ARG','Banfield','Liga ARG'],
['Cristian Fabbiani',42,'ARG','Newell\'s','Liga ARG'],
['Ricardo Zielinski',66,'ARG','Belgrano','Liga ARG'],
['Daniel Oldrá',57,'ARG','Instituto ACC','Liga ARG'],
['Omar De Felippe',64,'ARG','Central Córdoba','Liga ARG'],
['Rubén Insúa',64,'ARG','Barracas C.','Liga ARG'],
['Mariano Soso',45,'ARG','Defensa','Liga ARG'],
['Diego Dabove',52,'ARG','Tigre','Liga ARG'],
['Cristian González',51,'ARG','Platense','Liga ARG'],
['Leonardo Madelón',62,'ARG','Unión Santa Fe','Liga ARG'],
['Lucas Pusineri',50,'ARG','Atl. Tucumán','Liga ARG'],
['Facundo Sava',51,'ARG','Sarmiento Junin','Liga ARG'],
['Guillermo Farré',45,'ARG','Aldosivi','Liga ARG'],
['Alfredo Berti',57,'ARG','Ind. Rivadavia','Liga ARG'],
['Gustavo Benítez',51,'PAR','Dep. Riestra','Liga ARG'],
['Walter Ribonetto',47,'ARG','Godoy Cruz','Liga ARG'],
['Alejandro Orfila',50,'URU','Gimnasia','Liga ARG'],
// ── ESPAÑA ──
['Xabi Alonso',44,'ESP','Real Madrid','España'],
['Hansi Flick',61,'ALE','Barcelona','España'],
['Diego Simeone',55,'ARG','Atlético','España'],
['Matías Almeyda',52,'ARG','Sevilla FC','España'],
['Manuel Pellegrini',72,'CHI','Real Betis','España'],
['Marcelino García',60,'ESP','Villarreal','España'],
['Ernesto Valverde',62,'ESP','Athletic Club','España'],
['Carlos Corberán',43,'ESP','Valencia','España'],
['Claudio Giráldez',38,'ESP','Celta de Vigo','España'],
['José Bordalás',61,'ESP','Getafe','España'],
['Íñigo Pérez',38,'ESP','Rayo Vallecano','España'],
['Eduardo Coudet',51,'ARG','Alavés','España'],
['Jagoba Arrasate',47,'ESP','RCD Mallorca','España'],
['Míchel Sánchez',50,'ESP','Girona','España'],
['Eder Sarabia',45,'ESP','Elche CF','España'],
['Manolo González',47,'ESP','Espanyol','España'],
['Sergio Francisco',47,'ESP','Real Sociedad','España'],
// ── PREMIER ──
['Pep Guardiola',55,'ESP','Man City','Premier'],
['Arne Slot',47,'HOL','Liverpool','Premier'],
['Mikel Arteta',43,'ESP','Arsenal','Premier'],
['Enzo Maresca',46,'ITA','Chelsea','Premier'],
['Ruben Amorim',41,'POR','Man Utd','Premier'],
['Thomas Frank',52,'DIN','Tottenham','Premier'],
['Eddie Howe',48,'ING','Newcastle','Premier'],
['Unai Emery',54,'ESP','Aston Villa','Premier'],
['Fabian Hürzeler',33,'ALE','Brighton','Premier'],
['Andoni Iraola',43,'ESP','Bournemouth','Premier'],
['Keith Andrews',45,'IRL','Brentford','Premier'],
['Oliver Glasner',51,'AUT','Crystal Palace','Premier'],
['David Moyes',62,'ESC','Everton','Premier'],
['Marco Silva',48,'POR','Fulham','Premier'],
['Sean Dyche',54,'ING','Nott\'m Forest','Premier'],
['Daniel Farke',49,'ALE','Leeds','Premier'],
['Régis Le Bris',50,'FRA','Sunderland','Premier'],
['Scott Parker',45,'ING','Burnley','Premier'],
// ── ITALIA ──
['Cristian Chivu',45,'RUM','Inter','Italia'],
['Antonio Conte',56,'ITA','Napoli','Italia'],
['Luciano Spalletti',67,'ITA','Juventus','Italia'],
['Massimiliano Allegri',58,'ITA','AC Milan','Italia'],
['Gian Piero Gasperini',68,'ITA','Roma','Italia'],
['Raffaele Palladino',41,'ITA','Atalanta','Italia'],
['Vincenzo Italiano',48,'ITA','Bologna','Italia'],
['Maurizio Sarri',67,'ITA','Lazio','Italia'],
['Paolo Vanoli',53,'ITA','Fiorentina','Italia'],
['Cesc Fàbregas',38,'ESP','Como','Italia'],
['Marco Baroni',62,'ITA','Torino','Italia'],
['Kosta Runjaic',54,'ALE','Udinese','Italia'],
['Daniele De Rossi',42,'ITA','Genoa','Italia'],
['Eusebio Di Francesco',56,'ITA','Lecce','Italia'],
['Fabio Pisacane',40,'ITA','Cagliari','Italia'],
['Carlos Cuesta',30,'ESP','Parma','Italia'],
['Fabio Grosso',48,'ITA','Sassuolo','Italia'],
['Davide Nicola',53,'ITA','Cremonese','Italia'],
['Alberto Gilardino',43,'ITA','Pisa','Italia'],
['Paolo Zanetti',43,'ITA','Hellas Verona','Italia'],
// ── ALEMANIA ──
['Vincent Kompany',39,'BEL','Bayern Munich','Alemania'],
['Kasper Hjulmand',53,'DIN','Leverkusen','Alemania'],
['Niko Kovac',54,'CRO','Dortmund','Alemania'],
['Ole Werner',37,'ALE','Leipzig','Alemania'],
['Sebastian Hoeneß',43,'ALE','Stuttgart','Alemania'],
['Dino Toppmöller',45,'ALE','Frankfurt','Alemania'],
['Julian Schuster',40,'ALE','Freiburg','Alemania'],
['Bo Henriksen',51,'DIN','Mainz','Alemania'],
['Steffen Baumgart',54,'ALE','Union Berlin','Alemania'],
['Eugen Polanski',39,'ALE','Mönchengladbach','Alemania'],
['Horst Steffen',56,'ALE','Werder Bremen','Alemania'],
['Sandro Wagner',38,'ALE','Augsburg','Alemania'],
['Christian Ilzer',48,'AUT','Hoffenheim','Alemania'],
['Merlin Polzin',35,'ALE','Hamburg','Alemania'],
['Lukas Kwasniok',44,'ALE','1.FC Köln','Alemania'],
// ── FRANCIA ──
['Luis Enrique',55,'ESP','PSG','Francia'],
['Roberto De Zerbi',46,'ITA','Marseille','Francia'],
['Sébastien Pocognoli',38,'BEL','Monaco','Francia'],
['Paulo Fonseca',52,'POR','Lyon','Francia'],
['Bruno Genesio',59,'FRA','Lille','Francia'],
['Pierre Sage',46,'FRA','Lens','Francia'],
['Franck Haise',54,'FRA','Nice','Francia'],
['Habib Beye',48,'SEN','Stade Rennais','Francia'],
['Liam Rosenior',41,'ING','R. Strasbourg','Francia'],
['Eric Roy',58,'FRA','Stade Brestois','Francia'],
['Christophe Pélissier',60,'FRA','AJ Auxerre','Francia'],
['Didier Digard',39,'FRA','Le Havre AC','Francia'],
['Alexandre Dujeux',47,'FRA','Angers SCO','Francia'],
['Stéphane Gilli',51,'FRA','Paris FC','Francia'],
['Olivier Pantaloni',59,'FRA','FC Lorient','Francia'],
['Carles Martínez',41,'ESP','Toulouse','Francia'],
// ── BRASIL ──
['Filipe Luís',40,'BRA','Flamengo','Brasil'],
['Abel Ferreira',47,'POR','Palmeiras','Brasil'],
['Hernán Crespo',50,'ARG','São Paulo','Brasil'],
['Davide Ancelotti',36,'ITA','Botafogo','Brasil'],
['Leonardo Jardim',51,'POR','Cruzeiro','Brasil'],
['Jorge Sampaoli',65,'ARG','Atlético-MG','Brasil'],
['Mano Menezes',63,'BRA','Grêmio','Brasil'],
['Ramón Díaz',66,'ARG','Internacional','Brasil'],
['Dorival Júnior',63,'BRA','Corinthians','Brasil'],
['Juan Pablo Vojvoda',50,'ARG','Santos','Brasil'],
['Luis Zubeldía',45,'ARG','Fluminense','Brasil'],
['Fernando Diniz',51,'BRA','Vasco da Gama','Brasil'],
['Rogério Ceni',53,'BRA','EC Bahia','Brasil']
];
