// DTs — FUSIÓN de la extracción nueva con la base curada a mano.
// ⚠️ NO pisar este archivo con la salida del extractor: trae los nombres y
//    los clubes, pero CERO edades, CERO nacionalidades y ningún DT libre.
// [nombre,edad,nac,club,liga]
// 662 DTs · 618 clubes cubiertos · 128 con edad y nacionalidad · 44 libres
window.DTS_DB=[
['Diego Flores',0,'','Instituto ACC','Liga ARG'],
['Guillermo Barros Schelotto',53,'ARG','Vélez Sarsfield','Liga ARG'],
['Julio Vaccari',0,'','Defensa','Liga ARG'],
['Darío Franco',0,'','Gimnasia (M)','Liga ARG'],
['Rodolfo Arruabarrena',0,'','Boca Juniors','Liga ARG'],
['Jádson Viera',0,'','Independiente','Liga ARG'],
['Mauricio Pellegrino',54,'ARG','Lanús','Liga ARG'],
['Frank Darío Kudelka',0,'','Newell\'s','Liga ARG'],
['Rubén Insúa',64,'ARG','San Lorenzo','Liga ARG'],
['Alexander Medina',0,'','Estudiantes LP','Liga ARG'],
['Guillermo Duró',0,'','Dep. Riestra','Liga ARG'],
['Martín Palermo',0,'','Platense','Liga ARG'],
['Omar De Felippe',64,'ARG','CA Talleres','Liga ARG'],
['Sebastián Domínguez',0,'','Central Córdoba','Liga ARG'],
['Nicolás Diez',44,'ARG','Argentinos Jrs.','Liga ARG'],
['Jorge Almirón',0,'','Rosario Central','Liga ARG'],
['Alfredo Berti',57,'ARG','Ind. Rivadavia','Liga ARG'],
['Ariel Pereyra',0,'','Gimnasia','Liga ARG'],
['Diego Martínez',0,'','Huracán','Liga ARG'],
['Facundo Sava',51,'ARG','Sarmiento Junin','Liga ARG'],
['Leonardo Ponzio',0,'','River Plate','Liga ARG'],
['Julio César Falcioni',0,'','Atl. Tucumán','Liga ARG'],
['Diego Dabove',52,'ARG','Tigre','Liga ARG'],
['Damián Ayude',49,'ARG','Barracas C.','Liga ARG'],
['Pedro Troglio',60,'ARG','Banfield','Liga ARG'],
['Javier Sanguinetti',0,'','Aldosivi','Liga ARG'],
['Juan Pablo Vojvoda',50,'ARG','Racing Club','Liga ARG'],
['Rubén Forestello',0,'','Estudiantes RC','Liga ARG'],
['Juan Sara',0,'','Ferro','Liga ARG'],
['Walter Otta',0,'','Dep. Morón','Liga ARG'],
['Pablo de Muner',0,'','Godoy Cruz','Liga ARG'],
['Luis García',0,'','Dep. Madryn','Liga ARG'],
['Iván Delfino',0,'','Colon','Liga ARG'],
['Andrés Montenegro',0,'','Almirante Brown','Liga ARG'],
['Alfredo Grelak',0,'','Estudiantes','Liga ARG'],
['Diego Funes',0,'','Ciudad Bolívar','Liga ARG'],
['César Monasterio',0,'','Los Andes','Liga ARG'],
['Pedro Llorens',0,'','Chaco For Ever','Liga ARG'],
['César Vigevani',0,'','Def. Belgrano','Liga ARG'],
['Gustavo Coleoni',0,'','Racing (Cba)','Liga ARG'],
['Mauricio Giganti',0,'','All Boys','Liga ARG'],
['Claudio Biaggio',0,'','Mitre (SdE)','Liga ARG'],
['Alexis Matteo',0,'','Central Norte','Liga ARG'],
['Matías Módolo',0,'','San Miguel','Liga ARG'],
['Aníbal Biggeri',0,'','San Telmo','Liga ARG'],
['Tobías Kohan',0,'','Acassuso','Liga ARG'],
['José María Martínez',0,'','Tristán Suárez','Liga ARG'],
['Nicolás Domingo',0,'','CA Temperley','Liga ARG'],
['Hernán Pellerano',0,'','Gimnasia (J)','Liga ARG'],
['Cristian Pellerano',0,'','Atlanta','Liga ARG'],
['Joaquín Iturrería',0,'','Midland','Liga ARG'],
['Alejandro Schiapparelli',0,'','San Martín (SJ)','Liga ARG'],
['Juan Manuel Azconzábal',0,'','Gimnasia y Tiro','Liga ARG'],
['Fernando Quiroz',0,'','Atl. Rafaela','Liga ARG'],
['Mariano Echeverría',0,'','Dep. Maipú','Liga ARG'],
['Alejandro Orfila',50,'URU','San Martín (T)','Liga ARG'],
['Gabriel Gómez',0,'','Agropecuario','Liga ARG'],
['Emanuel Tripodi',0,'','Quilmes','Liga ARG'],
['Carlos Mayor',0,'','Almagro','Liga ARG'],
['Gastón Lotitto',0,'','Nueva Chicago','Liga ARG'],
['Marcelo Fuentes',0,'','Patronato','Liga ARG'],
['Sergio Rondina',0,'','Chacarita Jrs.','Liga ARG'],
['Mario Gómez',0,'','CA Güemes','Liga ARG'],
['David Hubert',0,'','Union SG','Bélgica'],
['Rik De Mil',0,'','KAA Gent','Bélgica'],
['Ivan Leko',0,'','Club Brugge','Bélgica'],
['Mario Kohnen',0,'','R Charleroi SC','Bélgica'],
['Vítor Bruno',0,'','Anderlecht','Bélgica'],
['Michael Beale',0,'','Zulte Waregem','Bélgica'],
['Vincent Euvrard',0,'','Standard Liège','Bélgica'],
['Issame Charaï',0,'','KVC Westerlo','Bélgica'],
['Tim Bakens',0,'','SK Beveren','Bélgica'],
['Jess Thorup',0,'','Genk','Bélgica'],
['Frédéric De Meyer',0,'','Sint-Truiden','Bélgica'],
['Lee Johnson',0,'','Lommel SK','Bélgica'],
['Marvin Compper',0,'','Royal Antwerp','Bélgica'],
['Edward Still',0,'','La Louvière','Bélgica'],
['Timmy Simons',0,'','OH Leuven','Bélgica'],
['Christophe Lepoint',0,'','KV Kortrijk','Bélgica'],
['Lars Friis',0,'','Cercle Brugge','Bélgica'],
['Frederik Vanderbiest',0,'','KV Mechelen','Bélgica'],
['Pablo Godoy',0,'','Always Ready','Bolivia'],
['Alejandro Restrepo',0,'','Bolívar','Bolivia'],
['Antônio Carlos Zago',0,'','The Strongest','Bolivia'],
['Bolívia',0,'','SA Bulo Bulo','Bolivia'],
['Cristian Paulucci',0,'','Club Blooming','Bolivia'],
['Juan Pablo Grass',0,'','Ind. Petrolero','Bolivia'],
['Leonardo Eguez',0,'','Guabirá','Bolivia'],
['Artur Costa',0,'','GV San José','Bolivia'],
['David Díaz',0,'','Aurora','Bolivia'],
['Jorge Alfonso',0,'','Real Tomayapo','Bolivia'],
['Gustavo Florentín',0,'','Oriente P.','Bolivia'],
['Marcelo Straccia',0,'','Real Oruro','Bolivia'],
['Yimmy Gutiérrez',0,'','Univ. de Vinto','Bolivia'],
['Wálter Flores',0,'','Club A.B.B.','Bolivia'],
['Guto Ferreira',0,'','Vila Nova FC','Brasil'],
['Enderson Moreira',0,'','Novorizontino','Brasil'],
['Paulo Autuori',0,'','Fortaleza','Brasil'],
['Maurício Barbieri',0,'','Juventude','Brasil'],
['Luizinho Lopes',0,'','Operário-PR','Brasil'],
['Umberto Louzer',0,'','Criciúma','Brasil'],
['Roger Silva',0,'','Atlético-GO','Brasil'],
['Fábio Matias',0,'','CRB','Brasil'],
['Mariano Soso',45,'ARG','Sport Recife','Brasil'],
['Eduardo Barros',0,'','Cuiabá-MT','Brasil'],
['Mozart',0,'','Goiás','Brasil'],
['Vinícius',0,'','São Bernardo','Brasil'],
['Alex',0,'','Athletic','Brasil'],
['Dudu Capixaba',0,'','Náutico','Brasil'],
['Daniel Paulista',0,'','Ceará SC','Brasil'],
['Claudio Tencati',0,'','Botafogo-SP','Brasil'],
['Allan Aal',0,'','Avaí FC','Brasil'],
['Rogério Micale',0,'','Londrina-PR','Brasil'],
['Douglas Leite',0,'','América-MG','Brasil'],
['Gilson Kleina',0,'','Ponte Preta','Brasil'],
['Fernando Ortiz',0,'','Colo-Colo','Chile'],
['Daniel Garnero',0,'','U. Católica','Chile'],
['Fernando Gago',0,'','U. de Chile','Chile'],
['Walter Ribonetto',47,'ARG','CD Everton','Chile'],
['Guillermo Farré',45,'ARG','Palestino','Chile'],
['Víctor Rivero',0,'','Limache','Chile'],
['Juan José Ribera',0,'','Ñublense','Chile'],
['Fernando Díaz',0,'','D. Concepción','Chile'],
['Felipe Gutiérrez',0,'','La Serena','Chile'],
['Hernán Caputto',0,'','Coquimbo Unido','Chile'],
['Patricio Graff',0,'','Audax Italiano','Chile'],
['Jaime García',0,'','Huachipato','Chile'],
['Lucas Bovaglio',0,'','O\'Higgins','Chile'],
['Gustavo Huerta',0,'','Cobresal','Chile'],
['Cristián Muñoz',0,'','U. Concepción','Chile'],
['John Armijo',0,'','La Calera','Chile'],
['David González',0,'','CD América','Colombia'],
['Pablo Peirano',0,'','A. Bucaramanga','Colombia'],
['Alberto Gamero',0,'','Millonarios','Colombia'],
['Lucas González Vélez',0,'','Atl. Nacional','Colombia'],
['Luis Amaranto Perea',0,'','Indep. Medellín','Colombia'],
['Rafael Dudamel',0,'','Deportivo Cali','Colombia'],
['Sebastián Oliveros',0,'','Deportes Tolima','Colombia'],
['Pablo Repetto',0,'','Indep. Santa Fe','Colombia'],
['José Luis García',0,'','Llaneros FC','Colombia'],
['Flavio Robatto',0,'','Rionegro Águila','Colombia'],
['Ricardo Valiño',0,'','Inter Bogotá','Colombia'],
['Jhon Jaime Gómez',0,'','Boyacá Chicó','Colombia'],
['Hernán Herrera',0,'','Once Caldas','Colombia'],
['Nicolás Chiesa',0,'','Cúcuta Dep.','Colombia'],
['Diego Arias',0,'','Fortaleza CEIF','Colombia'],
['Marc Reixats',0,'','Deportivo Pasto','Colombia'],
['Flabio Torres',0,'','Alianza FC','Colombia'],
['Arturo Reyes',0,'','Pereira','Colombia'],
['Hubert Bodhert',0,'','Jaguares FC','Colombia'],
['Sebastián Viera',0,'','Junior FC','Colombia'],
['Joaquín Papa',0,'','Independiente','Ecuador'],
['Diego Martínez',0,'','Uni. Católica','Ecuador'],
['Guillermo Sanguinetti',0,'','CD Macará','Ecuador'],
['Norberto Araujo',0,'','SD Aucas','Ecuador'],
['Gustavo Álvarez',0,'','LDU Quito','Ecuador'],
['Pablo Trobbiani',0,'','Barcelona SC','Ecuador'],
['Jorge Célico',0,'','Libertad FC','Ecuador'],
['Matías Córdoba',0,'','Leones FC','Ecuador'],
['Pool Gavilánez',0,'','Guayaquil City','Ecuador'],
['Ezequiel Medrán',0,'','CS Emelec','Ecuador'],
['Paúl Vélez',0,'','Mushuc Runa SC','Ecuador'],
['Raúl Becerra',0,'','Dep. Cuenca','Ecuador'],
['Juan Pablo Buch',0,'','Orense SC','Ecuador'],
['Ismael Blanco',0,'','Técnico U.','Ecuador'],
['Juan Carlos León',0,'','Delfín SC','Ecuador'],
['Raúl Duarte',0,'','Manta FC','Ecuador'],
['Enzo Maresca',46,'ITA','Man City','Premier'],
['Mikel Arteta',43,'ESP','Arsenal','Premier'],
['Fabian Hürzeler',33,'ALE','Brighton','Premier'],
['Daniel Farke',49,'ALE','Leeds','Premier'],
['Andoni Iraola',43,'ESP','Liverpool','Premier'],
['David Moyes',62,'ESC','Everton','Premier'],
['Sergej Jakirovic',0,'','Hull City','Premier'],
['Matthias Jaissle',0,'','Newcastle','Premier'],
['Xabi Alonso',44,'ESP','Chelsea','Premier'],
['Gary O\'Neil',0,'','Ipswich','Premier'],
['Michael Carrick',0,'','Man Utd','Premier'],
['Oliver Glasner',51,'AUT','Nott\'m Forest','Premier'],
['Régis Le Bris',50,'FRA','Sunderland','Premier'],
['Pierre Sage',46,'FRA','Crystal Palace','Premier'],
['Unai Emery',54,'ESP','Aston Villa','Premier'],
['Marco Rose',0,'','Bournemouth','Premier'],
['Frank Lampard',0,'','Coventry','Premier'],
['Álvaro Arbeloa',0,'','Fulham','Premier'],
['Roberto De Zerbi',46,'ITA','Tottenham','Premier'],
['Vítor Matos',0,'','Swansea','Premier'],
['Nuno Espírito Santo',0,'','West Ham','Premier'],
['Kim Hellberg',0,'','Middlesbrough','Premier'],
['César Peixoto',0,'','Wolves','Premier'],
['James Morrison',0,'','West Brom','Premier'],
['Julien Stéphan',0,'','QPR','Premier'],
['Mark Robins',0,'','Stoke City','Premier'],
['Michael Skubala',0,'','Bristol City','Premier'],
['Nathan Jones',0,'','Charlton','Premier'],
['Chris Davies',0,'','Birmingham','Premier'],
['Alex Neil',0,'','Millwall','Premier'],
['Tom Shaw',0,'','Lincoln City','Premier'],
['Tonda Eckert',0,'','Southampton','Premier'],
['Phil Parkinson',0,'','Wrexham','Premier'],
['Steven Schumacher',0,'','Bolton','Premier'],
['Tony Mowbray',0,'','Blackburn','Premier'],
['Philippe Clement',0,'','Norwich','Premier'],
['Chris Wilder',0,'','Sheff Utd','Premier'],
['John Mousinho',0,'','Portsmouth','Premier'],
['Alessio Dionisi',0,'','Watford','Premier'],
['Brian Barry-Murphy',0,'','Cardiff','Premier'],
['John Eustace',0,'','Derby','Premier'],
['Jason Euell',0,'','Preston','Premier'],
['Nicky Hayen',0,'','Burnley','Premier'],
['Filipe Luís',40,'BRA','Monaco','Francia'],
['Paulo Fonseca',52,'POR','Lyon','Francia'],
['Liam Rosenior',41,'ING','Paris FC','Francia'],
['Davide Ancelotti',36,'ITA','Lille','Francia'],
['Franck Haise',54,'FRA','Rennes','Francia'],
['Luis Enrique',55,'ESP','PSG','Francia'],
['Stéphane Gilli',51,'FRA','Angers SCO','Francia'],
['Hugo Oliveira',0,'','R. Strasbourg','Francia'],
['Patrick Videira',0,'','Le Mans FC','Francia'],
['Will Still',0,'','AJ Auxerre','Francia'],
['Julien Lachuer',0,'','Stade Brestois','Francia'],
['Alexandre Dujeux',47,'FRA','FC Lorient','Francia'],
['Jens Berthel Askou',0,'','Toulouse','Francia'],
['Olivier Pantaloni',59,'FRA','Nice','Francia'],
['Yannick Cahuzac',0,'','Lens','Francia'],
['Stéphane Dumont',0,'','Troyes','Francia'],
['Bruno Genesio',59,'FRA','Marseille','Francia'],
['Didier Digard',39,'FRA','Le Havre AC','Francia'],
['Ian Cathro',0,'','Saint-Étienne','Francia'],
['Damien Perrinelle',0,'','Red Star FC','Francia'],
['Nicolas Usaï',0,'','Stade Reims','Francia'],
['Zoumana Camara',0,'','Montpellier','Francia'],
['Luc Holtz',0,'','FC Metz','Francia'],
['Oswald Tanchot',0,'','AS Nancy','Francia'],
['Laurent Guyot',0,'','FC Annecy','Francia'],
['Vincent Hognon',0,'','FC Sochaux','Francia'],
['Baptiste Ridira',0,'','Dijon','Francia'],
['Thierry Debès',0,'','Pau FC','Francia'],
['Albert Sánchez',0,'','USL Dunkerque','Francia'],
['Sylvain Ripoll',0,'','Guingamp','Francia'],
['Olivier Frapolli',0,'','Grenoble','Francia'],
['Didier Santini',0,'','Rodez AF','Francia'],
['Grégory Poirier',0,'','FC Nantes','Francia'],
['David Guion',0,'','Clermont Foot','Francia'],
['Fabien Dagneaux',0,'','US Boulogne','Francia'],
['David Vignes',0,'','Stade Lavallois','Francia'],
['Niko Kovac',54,'CRO','Dortmund','Alemania'],
['Vincent Kompany',39,'BEL','Bayern Munich','Alemania'],
['Julian Schuster',40,'ALE','Freiburg','Alemania'],
['Manuel Baum',0,'','Augsburg','Alemania'],
['Carles Martínez',41,'ESP','Leverkusen','Alemania'],
['Urs Fischer',0,'','Mainz','Alemania'],
['Vincent Wagner',0,'','SV Elversberg','Alemania'],
['Martín Demichelis',0,'','Leipzig','Alemania'],
['Adi Hütter',0,'','Frankfurt','Alemania'],
['Miron Muslic',0,'','FC Schalke 04','Alemania'],
['Ralf Kettemann',0,'','SC Paderborn','Alemania'],
['René Wagner',0,'','1.FC Köln','Alemania'],
['Christian Ilzer',48,'AUT','Hoffenheim','Alemania'],
['Sebastian Hoeneß',43,'ALE','Stuttgart','Alemania'],
['Merlin Polzin',35,'ALE','Hamburg','Alemania'],
['Mauro Lustrinelli',0,'','Union Berlin','Alemania'],
['Alexander Blessin',0,'','Mönchengladbach','Alemania'],
['Stefan Leitl',0,'','Hertha BSC','Alemania'],
['Miroslav Klose',0,'','1.FC Nuremberg','Alemania'],
['Tobias Strobl',0,'','Wolfsburg','Alemania'],
['Torsten Lieberknecht',0,'','1.FC K\'lautern','Alemania'],
['Petrik Sander',0,'','1.FC Magdeburg','Alemania'],
['Claus-Dieter Wollitz',0,'','Energie Cottbus','Alemania'],
['Marcel Rapp',0,'','St. Pauli','Alemania'],
['Uwe Rösler',0,'','VfL Bochum','Alemania'],
['Sandro Wagner',38,'ALE','Hannover 96','Alemania'],
['Timo Schultz',0,'','VfL Osnabrück','Alemania'],
['Heiko Vogel',0,'','Greuther Fürth','Alemania'],
['Oliver Kirch',0,'','Arm. Bielefeld','Alemania'],
['Maximilian Senft',0,'','Karlsruher SC','Alemania'],
['Tim Walter',0,'','Holstein Kiel','Alemania'],
['Thomas Stamm',0,'','Dynamo Dresden','Alemania'],
['Florian Kohfeldt',0,'','Darmstadt 98','Alemania'],
['Jacob Neestrup',0,'','Panathinaikos','Grecia'],
['Alessio Lisci',0,'','PAOK','Grecia'],
['Marko Nikolic',0,'','AEK Athens','Grecia'],
['Christos Kontis',0,'','OFI Crete','Grecia'],
['Imanol Alguacil',0,'','Olympiacos','Grecia'],
['Giannis Anastasiou',0,'','Panetolikos','Grecia'],
['Michalis Grigoriou',0,'','Aris Saloniki','Grecia'],
['Walter Mazzarri',0,'','Iraklis','Grecia'],
['Sebastián Leto',0,'','Kifisia','Grecia'],
['Panagiotis Christofileas',0,'','Kalamata','Grecia'],
['Dusan Kerkez',0,'','Atromitos','Grecia'],
['Georgios Antonopoulos',0,'','Asteras Aktor','Grecia'],
['Konstantinos Bratsos',0,'','Volos','Grecia'],
['Elias Charalambous',0,'','Levadiakos','Grecia'],
['Gian Piero Gasperini',68,'ITA','Roma','Italia'],
['Cristian Chivu',45,'RUM','Inter','Italia'],
['Gennaro Gattuso',0,'','Lazio','Italia'],
['Fabio Pisacane',40,'ITA','Cagliari','Italia'],
['Ruben Amorim',41,'POR','AC Milan','Italia'],
['Massimiliano Alvini',0,'','Frosinone','Italia'],
['Luciano Spalletti',67,'ITA','Juventus','Italia'],
['Cesc Fàbregas',38,'ESP','Como','Italia'],
['Massimiliano Allegri',58,'ITA','Napoli','Italia'],
['Alberto Aquilani',0,'','Sassuolo','Italia'],
['Maurizio Sarri',67,'ITA','Atalanta','Italia'],
['Eusebio Di Francesco',56,'ITA','Lecce','Italia'],
['Kosta Runjaić',54,'ALE','Udinese','Italia'],
['Ignazio Abate',0,'','Torino','Italia'],
['Carlos Cuesta',30,'ESP','Parma','Italia'],
['Ivan Jurić',0,'','Monza','Italia'],
['Paolo Vanoli',53,'ITA','Fiorentina','Italia'],
['Raffaele Palladino',41,'ITA','Bologna','Italia'],
['Daniele De Rossi',42,'ITA','Genoa','Italia'],
['Giovanni Stroppa',0,'','Venezia','Italia'],
['Guillermo Almada',0,'','América','Liga MX'],
['Miguel Herrera',0,'','Atlante','Liga MX'],
['Hernán Crespo',50,'ARG','Atlas','Liga MX'],
['Joel Huiqui',0,'','CD Cruz Azul','Liga MX'],
['Sebastián Abreu',0,'','Club Tijuana','Liga MX'],
['Tomás Campos',0,'','FC Juárez','Liga MX'],
['Javier Gandolfi',0,'','León','Liga MX'],
['Matías Almeyda',52,'ARG','Monterrey','Liga MX'],
['Marcos Villano',0,'','Necaxa','Liga MX'],
['Benjamín Mora',0,'','Pachuca','Liga MX'],
['Albert Espigares',0,'','Puebla FC','Liga MX'],
['Esteban González',0,'','Querétaro FC','Liga MX'],
['Diego Mejía',0,'','San Luis','Liga MX'],
['Renato Paiva',0,'','Santos Laguna','Liga MX'],
['Víctor Manuel Vucetich',0,'','Tigres UANL','Liga MX'],
['Antonio Mohamed',0,'','Toluca','Liga MX'],
['Esteban Solari',0,'','UNAM Pumas','Liga MX'],
['Lee-Roy Echteld',0,'','AZ Alkmaar','Holanda'],
['Giovanni van Bronckhorst',0,'','Feyenoord','Holanda'],
['Peter Bosz',0,'','PSV','Holanda'],
['John van den Brom',0,'','FC Twente','Holanda'],
['Míchel Sánchez',50,'ESP','Ajax','Holanda'],
['Danny Buijs',0,'','Fortuna Sittard','Holanda'],
['Ruben den Uil',0,'','Excelsior','Holanda'],
['Dick Lukkien',0,'','FC Groningen','Holanda'],
['Joseph Oosting',0,'','Go Ahead Eagles','Holanda'],
['Robin Veldman',0,'','Heerenveen','Holanda'],
['Dick Schreuder',0,'','N.E.C.','Holanda'],
['Rogier Meijer',0,'','Sparta R.','Holanda'],
['Henk Brugge',0,'','Telstar','Holanda'],
['Johan Plat',0,'','SC Cambuur','Holanda'],
['Anthony Correia',0,'','Utrecht','Holanda'],
['Henry van der Vegt',0,'','PEC Zwolle','Holanda'],
['Robin Peter',0,'','ADO Den Haag','Holanda'],
['John Stegeman',0,'','Willem II','Holanda'],
['Eduardo Ledesma',0,'','2 de Mayo','Paraguay'],
['Nelson Valdez',0,'','Libertad','Paraguay'],
['Víctor Bernay',0,'','Nacional','Paraguay'],
['Pablo Sánchez',0,'','Olimpia','Paraguay'],
['Francisco Arce',0,'','Guaraní','Paraguay'],
['Roberto Nanni',0,'','CS Ameliano','Paraguay'],
['José Arrúa',0,'','Trinidense','Paraguay'],
['Gustavo Costas',63,'ARG','Cerro Porteño','Paraguay'],
['Lucas Barrios',0,'','Luqueño','Paraguay'],
['Javier Torrente',0,'','Rubio Ñú','Paraguay'],
['Jorge González',0,'','Recoleta FC','Paraguay'],
['Pablo Fornasari',0,'','CS San Lorenzo','Paraguay'],
['Lisandro Greppo',0,'','Dep. Garcilaso','Perú'],
['Héctor Cúper',0,'','Universitario','Perú'],
['Roberto Mosquera',0,'','Sport. Cristal','Perú'],
['Federico Urciuoli',0,'','Alianza Atl.','Perú'],
['Richard Pellejero',0,'','Sport Huancayo','Perú'],
['Jorge Araujo',0,'','Juan Pablo II','Perú'],
['Miguel Rondelli',0,'','FBC Melgar','Perú'],
['Javier Rabanal',0,'','Cusco FC','Perú'],
['Pablo Guede',0,'','Alianza Lima','Perú'],
['Gerardo Ameli',0,'','Atlético Grau','Perú'],
['Carlos Desio',0,'','Sport Boys','Perú'],
['José Eugenio Hernández',0,'','Comerciantes','Perú'],
['Celso Ayala',0,'','FC Cajamarca','Perú'],
['Horacio Melgarejo',0,'','Cienciano','Perú'],
['Jaime Serna',0,'','Dep. Moquegua','Perú'],
['Juan Carlos Bazalar',0,'','Los Chankas','Perú'],
['Víctor Rivera',0,'','AD Tarma','Perú'],
['Cristian Molins',0,'','UTC','Perú'],
['Francesco Farioli',0,'','Porto','Portugal'],
['Marco Silva',48,'POR','Benfica','Portugal'],
['Rui Borges',0,'','Sporting','Portugal'],
['Petit',0,'','Santa Clara','Portugal'],
['Vasco Seabra',0,'','Arouca','Portugal'],
['Carlos Vicens',0,'','Braga','Portugal'],
['Bruno Pinheiro',0,'','Académico Viseu','Portugal'],
['Pepa',0,'','Estrela Amadora','Portugal'],
['Luís Pinto',0,'','Gil Vicente','Portugal'],
['Sérgio Ferreira',0,'','Alverca','Portugal'],
['Mitchell van der Gaag',0,'','Marítimo','Portugal'],
['Vasco Botelho da Costa',0,'','Moreirense','Portugal'],
['Carlos Carvalhal',0,'','Famalicão','Portugal'],
['Tiago Margarido',0,'','Vit. Guimarães','Portugal'],
['Alexandre Santos',0,'','Nacional','Portugal'],
['Sotiris Sylaidopoulos',0,'','Rio Ave','Portugal'],
['Filipe Coelho',0,'','Casa Pia','Portugal'],
['Vasco Matos',0,'','Estoril','Portugal'],
['Ricardo Silva',0,'','Lus. Lourosa','Portugal'],
['José Manuel Aira',0,'','Penafiel','Portugal'],
['Tiago Fernandes',0,'','Sporting B','Portugal'],
['Ronald Molina',0,'','Vizela','Portugal'],
['Fábio Pereira',0,'','Leiria','Portugal'],
['Carlos Fangueiro',0,'','Leixões','Portugal'],
['Nélson Veríssimo',0,'','Benfica B','Portugal'],
['Ricardo Costa',0,'','Tondela','Portugal'],
['António Barbosa',0,'','Coimbra','Portugal'],
['José Faria',0,'','Farense','Portugal'],
['Alex',0,'','Portimonense','Portugal'],
['Sérgio Fonseca',0,'','Avs FS','Portugal'],
['Moreno',0,'','Felgueiras','Portugal'],
['Luís Tralhão',0,'','Torreense','Portugal'],
['Jorge Pinto',0,'','Amarante','Portugal'],
['Vítor Martins',0,'','Chaves','Portugal'],
['João Brandão',0,'','FC Porto B','Portugal'],
['Rui Ferreira',0,'','Feirense','Portugal'],
['Murad Musaev',0,'','Krasnodar','Rusia'],
['Sandro Schwarz',0,'','Dynamo Moscow','Rusia'],
['Juan Carlos Carcedo',0,'','Spartak Moscow','Rusia'],
['Dmitriy Igdisamov',0,'','CSKA Moscow','Rusia'],
['Sergey Semak',0,'','Zenit S-Pb','Rusia'],
['Franc Artiga',0,'','Rubin Kazan','Rusia'],
['Vadim Evseev',0,'','Dinamo Makhach.','Rusia'],
['Andrey Talalaev',0,'','Baltika','Rusia'],
['Sergey Bulatov',0,'','KS Samara','Rusia'],
['Stanislav Cherchesov',0,'','Akhmat Grozny','Rusia'],
['Ildar Akhmetzyanov',0,'','Orenburg','Rusia'],
['Dmitriy Kirichenko',0,'','Rostov','Rusia'],
['Srdjan Blagojevic',0,'','Akron Tolyatti','Rusia'],
['Mikhail Galaktionov',0,'','Loko Moscow','Rusia'],
['Barseg Kirakosyan',0,'','Rodina Moscow','Rusia'],
['Oleg Vasilenko',0,'','Fakel Voronezh','Rusia'],
['Hansi Flick',61,'ALE','Barcelona','España'],
['Diego Simeone',55,'ARG','Atlético','España'],
['Manuel Pellegrini',72,'CHI','Real Betis','España'],
['José Mourinho',0,'','Real Madrid','España'],
['Luis García',0,'','Sevilla FC','España'],
['Quique Sánchez Flores',0,'','Alavés','España'],
['Antonio Hidalgo',0,'','Dep. A Coruña','España'],
['Pellegrino Matarazzo',0,'','Real Sociedad','España'],
['Iñigo Pérez',38,'ESP','Villarreal','España'],
['Edin Terzic',0,'','Athletic Club','España'],
['José Bordalás',61,'ESP','Getafe','España'],
['Beñat San José',0,'','Rayo Vallecano','España'],
['Luis Miguel Ramis',0,'','CA Osasuna','España'],
['Claudio Giráldez',38,'ESP','Celta','España'],
['Manolo González',47,'ESP','Espanyol','España'],
['José Alberto López',0,'','Racing','España'],
['Luís Castro',0,'','Levante','España'],
['Martín Anselmi',0,'','Elche CF','España'],
['Javier Aguirre',0,'','Valencia','España'],
['Juan Funes',0,'','Málaga CF','España'],
['Pablo Hernández',0,'','Castellón','España'],
['Jokin Aranbarri',0,'','SD Eibar','España'],
['Quique Álvarez',0,'','Girona','España'],
['Luis García',0,'','RCD Mallorca','España'],
['Xavier García Pimienta',0,'','UD Almería','España'],
['Ferran Costa',0,'','CE Sabadell','España'],
['Sergio Francisco',47,'ESP','Burgos CF','España'],
['Rubén Albés',0,'','CD Leganés','España'],
['Álvaro Cervera',0,'','CD Tenerife','España'],
['Nicolás Larcamón',0,'','Sporting Gijón','España'],
['Rubén de la Barrera',0,'','UD Las Palmas','España'],
['Julián Calero',0,'','Real Oviedo','España'],
['Pacheta',0,'','Granada CF','España'],
['Ion Ansotegi',0,'','Real Sociedad B','España'],
['Carles Manso',0,'','FC Andorra','España'],
['Iván Ania',0,'','Córdoba CF','España'],
['Javier Calleja',0,'','Eldense','España'],
['Fran Escribá',0,'','Real Valladolid','España'],
['Albert Celades',0,'','Cádiz CF','España'],
['José Juan Romero',0,'','AD Ceuta','España'],
['Alberto González',0,'','Albacete','España'],
['Besnik Hasi',0,'','Amed SK','Turquía'],
['Okan Buruk',0,'','Galatasaray','Turquía'],
['Vincenzo Italiano',48,'ITA','Beşiktaş','Turquía'],
['Selçuk İnan',0,'','Kocaelispor','Turquía'],
['João Pereira',0,'','Alanyaspor','Turquía'],
['İsmail Kartal',0,'','Fenerbahçe','Turquía'],
['Thomas Reis',0,'','Trabzonspor','Turquía'],
['Emre Belözoğlu',0,'','Kasimpasa','Turquía'],
['Recep Uçar',0,'','C. Rizespor','Turquía'],
['Orhan Ak',0,'','Gaziantep FK','Turquía'],
['Burak Yılmaz',0,'','Corum FK','Turquía'],
['Nuri Şahin',0,'','Basaksehir','Turquía'],
['Metin Diyadin',0,'','Genclerbirligi','Turquía'],
['Serkan Özbalta',0,'','Erzurumspor FK','Turquía'],
['İlhan Palut',0,'','Konyaspor','Turquía'],
['Thorsten Fink',0,'','Samsunspor','Turquía'],
['Stanimir Stoilov',0,'','Göztepe','Turquía'],
['Erman Kılıç',0,'','Eyüpspor','Turquía'],
['B.J. Callaghan',0,'','Nashville','MLS'],
['Marko Mitrovic',0,'','New England','MLS'],
['Kily González',0,'','Miami','MLS'],
['Dean Smith',0,'','Charlotte','MLS'],
['Gregg Berhalter',0,'','Chicago','MLS'],
['Ryan Richter',0,'','Philadelphia','MLS'],
['Martín Perelman',0,'','Orlando','MLS'],
['Michael Bradley',0,'','New York','MLS'],
['Pat Noonan',0,'','Cincinnati','MLS'],
['Pascal Jansen',0,'','New York City','MLS'],
['René Weiler',0,'','D.C. United','MLS'],
['Robin Fraser',0,'','Toronto','MLS'],
['Laurent Courtois',0,'','Columbus','MLS'],
['Tata Martino',0,'','Atlanta','MLS'],
['Philippe Eullaffroy',0,'','Montréal','MLS'],
['Jesper Sørensen',0,'','Vancouver','MLS'],
['Ben Olsen',0,'','Houston','MLS'],
['Yoann Damet',0,'','St. Louis CITY','MLS'],
['Eric Quill',0,'','Dallas','MLS'],
['Bruce Arena',0,'','SJ Earthquakes','MLS'],
['Marc Dos Santos',0,'','LAFC','MLS'],
['Matt Wells',0,'','Colorado','MLS'],
['Greg Vanney',0,'','LA Galaxy','MLS'],
['Martí Cifuentes',0,'','Portland','MLS'],
['Brian Schmetzer',0,'','Seattle','MLS'],
['Mikey Varas',0,'','San Diego','MLS'],
['Davy Arnaud',0,'','Austin','MLS'],
['Pablo Mastroeni',0,'','Salt Lake','MLS'],
['Cameron Knowles',0,'','Minnesota','MLS'],
['Raphael Wicky',0,'','Kansas City','MLS'],
['Jorge Fossati',0,'','Liverpool FC','Uruguay'],
['Daniel Carreño',0,'','Nacional','Uruguay'],
['Diego Aguirre',0,'','Peñarol','Uruguay'],
['Alejandro Cappuccio',0,'','CA Cerro','Uruguay'],
['Sergio Blanco',0,'','Juventud','Uruguay'],
['Cristian Chambian',0,'','Racing Club','Uruguay'],
['Gabriel Di Noia',0,'','CD Maldonado','Uruguay'],
['Diego Jaume',0,'','Boston River','Uruguay'],
['Mathías Corujo',0,'','Wanderers','Uruguay'],
['Danielo Núñez',0,'','Cerro Largo','Uruguay'],
['Mauricio Larriera',0,'','Defensor SC','Uruguay'],
['Antonio Pacheco',0,'','Central Español','Uruguay'],
['Leonel Rocco',0,'','Danubio FC','Uruguay'],
['Federico Nieves',0,'','Albion FC','Uruguay'],
['Francesco Stifano',0,'','Metropolitanos','Venezuela'],
['Álvaro Recoba',0,'','Táchira','Venezuela'],
['Eduardo Saragó',0,'','Puerto Cabello','Venezuela'],
['Daniel Farías',0,'','Carabobo FC','Venezuela'],
['Leo González',0,'','Portuguesa FC','Venezuela'],
['Héctor Bidoglio',0,'','Dep. La Guaira','Venezuela'],
['Jesús Gómez',0,'','Estudiantes','Venezuela'],
['Luis De Oliveira',0,'','UCV FC','Venezuela'],
['Jesús Ortíz',0,'','Monagas SC','Venezuela'],
['Ronny Flores',0,'','Caracas FC','Venezuela'],
['Johannys Garcia',0,'','Rayo Zuliano','Venezuela'],
['Ronaldy Contreras',0,'','Trujillanos','Venezuela'],
['Josue Ortíz',0,'','Zamora FC','Venezuela'],
['Marcelo Zuleta',0,'','Anzoátegui','Venezuela'],
['Leonardo Madelón',62,'ARG','Unión Santa Fe','Liga ARG'],
['Ricardo Zielinski',66,'ARG','Belgrano','Liga ARG'],
['Leonardo Fernández',0,'','Colegiales','Liga ARG'],
['Giancarlo Umaña',0,'','Real Potosí','Bolivia'],
['Eduardo Villegas',0,'','Nacional Potosí','Bolivia'],
['Leonardo Jardim',51,'POR','Flamengo','Brasil'],
['Abel Ferreira',47,'POR','Palmeiras','Brasil'],
['Odair Hellmann',0,'','Athletico-PR','Brasil'],
['Marcão',0,'','Fluminense','Brasil'],
['Rogério Ceni',53,'BRA','EC Bahia','Brasil'],
['Artur Jorge',0,'','Cruzeiro','Brasil'],
['Fernando Seabra',0,'','Coritiba FC','Brasil'],
['Eduardo Domínguez',47,'ARG','Atlético-MG','Brasil'],
['Vagner Mancini',0,'','RB Bragantino','Brasil'],
['Dorival Júnior',63,'BRA','São Paulo','Brasil'],
['Jair Ventura',0,'','EC Vitória','Brasil'],
['Fernando Diniz',51,'BRA','Corinthians','Brasil'],
['Cuca',0,'','Santos','Brasil'],
['Rodrigo Bellão',0,'','Botafogo','Brasil'],
['Luís Castro',0,'','Grêmio','Brasil'],
['Rafael Guanaes',0,'','Mirassol-SP','Brasil'],
['Pedro Emanuel',0,'','Vasco da Gama','Brasil'],
['Paulo Pezzolano',0,'','Internacional','Brasil'],
['Léo Condé',0,'','Remo','Brasil'],
['Rafael Lacerda',0,'','Chapecoense','Brasil'],
['Keith Andrews',45,'IRL','Brentford','Premier'],
['Daniel Thioune',0,'','Werder Bremen','Alemania'],
['Frank Schmidt',0,'','Heidenheim','Alemania'],
['Lars Kornetka',0,'','E. Braunschweig','Alemania'],
['Filippo Inzaghi',0,'','Palermo','Italia'],
['Francesco Modesto',0,'','Mantova','Italia'],
['Davide Possanzini',0,'','Südtirol','Italia'],
['Francesco Tomei',0,'','Ascoli','Italia'],
['Paolo Bianco',0,'','Pisa','Italia'],
['Daniele Galloppa',0,'','Modena','Italia'],
['Alessandro Nesta',0,'','Avellino','Italia'],
['Guido Pagliuca',0,'','FC Empoli','Italia'],
['Alessandro Diamanti',0,'','Cesena','Italia'],
['Marco Baroni',62,'ITA','Hellas Verona','Italia'],
['Antonio Nicola Calabro',0,'','Padova','Italia'],
['Fabio Gallo',0,'','LR Vicenza','Italia'],
['Fabio Pecchia',0,'','Cremonese','Italia'],
['Cristian Bucchi',0,'','Arezzo','Italia'],
['Andrea Chiappella',0,'','Virtus Entella','Italia'],
['Gabriele Cioffi',0,'','Carrarese','Italia'],
['Antonio Floro Flores',0,'','Benevento','Italia'],
['Bernardo Corradi',0,'','Sampdoria','Italia'],
['Pietro De Giorgio',0,'','Juve Stabia','Italia'],
['Giorgio Gorgone',0,'','Catanzaro','Italia'],
['Gabriel Milito',0,'','Chivas','Liga MX'],
['Simone Inzaghi',0,'','Al-Hilal','Arabia'],
['Brendan Rodgers',0,'','Al-Qadsiah','Arabia'],
['Ange Postecoglou',0,'','Al-Nassr','Arabia'],
['Christophe Galtier',0,'','NEOM SC','Arabia'],
['Jens Wissing',0,'','Al-Ittihad','Arabia'],
['Arthur Papas',0,'','Al-Ettifaq','Arabia'],
['Des Buckingham',0,'','Al-Kholood','Arabia'],
['Marino Pusic',0,'','Al-Ahli','Arabia'],
['Jalel Kadri',0,'','Al-Hazem','Arabia'],
['Bruno Lage',0,'','Al-Diriyah','Arabia'],
['Fábio Carille',0,'','Al-Fayha','Arabia'],
['Maurício Dulac',0,'','Al-Riyadh','Arabia'],
['José Gomes',0,'','Al-Khaleej','Arabia'],
['Khaled Al-Atwi',0,'','Al-Fateh','Arabia'],
['Zarko Lazetic',0,'','Al-Taawoun','Arabia'],
['Giovanni Solinas',0,'','Al-Faisaly','Arabia'],
['Thomas Letsch',0,'','Al-Shabab','Arabia'],
['Damir Buric',0,'','Abha','Arabia'],
['Fredi Álvarez',0,'','Celta Fortuna','España'],
['Marcelo Méndez',0,'','Mvd City Torque','Uruguay'],
['Tabaré Silva',0,'','CA Progreso','Uruguay'],
['Claudio Úbeda',56,'ARG','','Liga ARG'],
['Marcelo Gallardo',50,'ARG','','Liga ARG'],
['Gustavo Quinteros',61,'ARG','','Liga ARG'],
['Carlos Tevez',42,'ARG','','Liga ARG'],
['Frank Kudelka',65,'ARG','','Liga ARG'],
['Cristian Fabbiani',42,'ARG','','Liga ARG'],
['Daniel Oldrá',57,'ARG','','Liga ARG'],
['Cristian González',51,'ARG','','Liga ARG'],
['Lucas Pusineri',50,'ARG','','Liga ARG'],
['Gustavo Benítez',51,'PAR','','Liga ARG'],
['Marcelino García',60,'ESP','','España'],
['Ernesto Valverde',62,'ESP','','España'],
['Jagoba Arrasate',47,'ESP','','España'],
['Eder Sarabia',45,'ESP','','España'],
['Pep Guardiola',55,'ESP','','Premier'],
['Arne Slot',47,'HOL','','Premier'],
['Thomas Frank',52,'DIN','','Premier'],
['Eddie Howe',48,'ING','','Premier'],
['Sean Dyche',54,'ING','','Premier'],
['Scott Parker',45,'ING','','Premier'],
['Antonio Conte',56,'ITA','','Italia'],
['Davide Nicola',53,'ITA','','Italia'],
['Alberto Gilardino',43,'ITA','','Italia'],
['Paolo Zanetti',43,'ITA','','Italia'],
['Kasper Hjulmand',53,'DIN','','Alemania'],
['Ole Werner',37,'ALE','','Alemania'],
['Bo Henriksen',51,'DIN','','Alemania'],
['Steffen Baumgart',54,'ALE','','Alemania'],
['Horst Steffen',56,'ALE','','Alemania'],
['Lukas Kwasniok',44,'ALE','','Alemania'],
['Sébastien Pocognoli',38,'BEL','','Francia'],
['Habib Beye',48,'SEN','','Francia'],
['Eric Roy',58,'FRA','','Francia'],
['Christophe Pélissier',60,'FRA','','Francia'],
['Mano Menezes',63,'BRA','','Brasil'],
['Ramón Díaz',66,'ARG','','Brasil'],
['Luis Zubeldía',45,'ARG','','Brasil'],
['Dino Toppmöller',45,'ALE','','Francia'],
['Eugen Polanski',39,'ALE','','Alemania'],
['Carlos Corberán',43,'ESP','','España'],
['Jorge Sampaoli',65,'ARG','','Liga ARG'],
['Eduardo Coudet',51,'ARG','','Liga ARG'],
['Fabio Grosso',48,'ITA','','Italia'],
['Ariel Holan',65,'ARG','','Paraguay'],
];
